name: Test backends (blocking)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-blocking-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Test curl
        run: cargo test -p nyquest-backend-tests --verbose --features blocking,curl,multipart

  test-blocking-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Test winrt
        run: cargo test -p nyquest-backend-tests --verbose --features blocking,winrt,multipart

  test-blocking-windows-winhttp:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Test winhttp
        run: cargo test -p nyquest-backend-tests --verbose --features blocking,winhttp,multipart

  test-blocking-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Test nsurlsession
        run: cargo test -p nyquest-backend-tests --verbose --features blocking,nsurlsession,multipart
  
  test-blocking-reqwest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Test reqwest
        run: cargo test -p nyquest-backend-tests --verbose --features blocking,reqwest,multipart
